name: clustering-images-pca
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - mrcfile
  - scikit-image
  - pip
  - pip:
      - multiprocess